print("Aegis pipeline alive")

# INTENTIONALLY INSECURE — REALISTIC AWS SECRET (FOR SAST TEST)
AWS_ACCESS_KEY_ID = "AKIA4ZQ9M8L2X7C1K9QW"
AWS_SECRET_ACCESS_KEY = "bR7cYxZPq9vM3N2EwLJ0TgHkA8sF4D1Ue6R"





