pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out source code'
            }
        }
        stage('Run App') {
            steps {
                sh 'python3 app/app.py'
            }
        }
    }
}
